# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master, development, '**-RC' ]
  workflow_dispatch:

permissions: {}

jobs:
  build:

    # As this action runs on every push to the default branch and uses quite a lot of resources (both minutes and caches),
    # only run it in the FreeTubeApp/FreeTube repository to avoid unnecessary GitHub Actions usage/billing in forks.
    # Still allow manually triggering the workflow.
    # If a fork does need this workflow to run on every push to the default branch, they can change this condition in their fork to include their repository.
    if: github.repository == 'FreeTubeApp/FreeTube' || github.event_name == 'workflow_dispatch'

    permissions:
      actions: write
      contents: read

    strategy:
      matrix:
        node-version: [24.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      with:
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"
    - run: yarn run ci
      shell: bash
      env:
        ELECTRON_SKIP_BINARY_DOWNLOAD: '1'
    - run: yarn run lint
      shell: bash
    - name: Set version number
      id: versionNumber
      shell: bash
      run: |
        original_version="$(jq -r '.version' package.json)"
        version="$original_version"

        lower_case_ref="$(echo -E "$GITHUB_REF" | tr '[:upper:]' '[:lower:]')"

        if [[ "$lower_case_ref" == *development* ]]; then
          version="${original_version}-nightly-${GITHUB_RUN_NUMBER}"
        elif [[ "$lower_case_ref" == *rc* ]]; then
          version="${original_version}-RC-${GITHUB_RUN_NUMBER}"
        fi

        package_json="$(jq --arg version "$version" '.version = $version' package.json)"

        echo -E "$package_json" > package.json
        echo "version=${version}" >> "$GITHUB_OUTPUT"

    - name: Install libarchive-tools
      shell: bash
      run: |
        sudo apt update
        sudo apt -y install libarchive-tools

    - name: Build x64 with Node.js ${{ matrix.node-version}}
      shell: bash
      run: yarn run build

    - name: Convert X64 AppImage to static runtime
      shell: bash
      env:
        VERSION: ${{ steps.versionNumber.outputs.version }}
      run: |
        sudo apt install desktop-file-utils
        cd build
        appimage="FreeTube-${VERSION}.AppImage"
        wget "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage" -O ./appimagetool.AppImage
        chmod +x ./"$appimage" ./appimagetool.AppImage
        ./"$appimage" --appimage-extract && rm -f ./"$appimage"
        ./appimagetool.AppImage --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 20 \
          -n ./squashfs-root ./"$appimage"
        rm -rf ./squashfs-root ./appimagetool.AppImage

    - name: Upload Linux .zip x64 Artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-linux-x64-portable.zip
        path: build/freetube-${{ steps.versionNumber.outputs.version }}.zip

    - name: Upload Linux .7z x64 Artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-linux-x64-portable.7z
        path: build/freetube-${{ steps.versionNumber.outputs.version }}.7z

    - name: Upload .deb x64 Artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
      with:
        name: freetube_${{ steps.versionNumber.outputs.version }}_amd64.deb
        path: build/freetube_${{ steps.versionNumber.outputs.version }}_amd64.deb

    - name: Upload AppImage x64 Artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-amd64.AppImage
        path: build/FreeTube-${{ steps.versionNumber.outputs.version }}.AppImage

    - name: Upload .rpm x64 Artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}.amd64.rpm
        path: build/freetube-${{ steps.versionNumber.outputs.version }}.x86_64.rpm

    - name: Upload Pacman .pacman x64 Artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-amd64.pacman
        path: build/freetube-${{ steps.versionNumber.outputs.version }}.pacman
